did initial html
michael5522/students-grade-table pull request #1
Opened 2020-11-20 04:43 UTC by michael5522

2020-11-22 05:45 UTC, michael5522 commented
<img width="1251" alt="Screen Shot 2020-11-21 at 9 43 45 PM" src="https://user-images.githubusercontent.com/55678486/99896170-d5b7fa80-2c42-11eb-91dd-279434f58307.png">

2020-11-23 23:20 UTC, TimelikeClosure requested changes
@michael5522 Please fix the issue below, then let me know so I can check it again.

2020-11-23 23:20 UTC, TimelikeClosure commented on components/grade-table-practice.js
> +  // }
Please remove commented code blocks when you're done with them.

2020-11-25 03:26 UTC, TimelikeClosure approved these changes

2020-11-25 04:01 UTC, merged